import awsServiceNames from "./awsServiceNames";

import awsServiceCategories from "./awsServiceCategories";

const hierarchy = {
    [awsServiceCategories.aiMl]: [awsServiceNames.awsSageMakerProject, awsServiceNames.awsSageMakerExperiment],
    [awsServiceCategories.analytics]: [
        awsServiceNames.awsEmrCluster,
        awsServiceNames.awsAthenaDataCatalog,
        awsServiceNames.awsGlueJob,
        awsServiceNames.awsGlueRegistry,
        awsServiceNames.awsKinesisFirehoseDeliveryStream,
        awsServiceNames.awsKinesisStream,
    ],
    [awsServiceCategories.compute]: [
        awsServiceNames.awsInstance,
        awsServiceNames.awsElasticBeanstalkEnvironment,
        awsServiceNames.awsEcsContainerDefinition,
        awsServiceNames.awsEcsTaskDefinition,
        awsServiceNames.awsEcsTask,
        awsServiceNames.awsEcsService,
        awsServiceNames.awsEbsVolume,
        awsServiceNames.awsAutoscalingGroup,
        awsServiceNames.awsLambdaFunction,
        awsServiceNames.awsElasticBeanstalkApplication,
        awsServiceNames.awsEksCluster,
        awsServiceNames.awsEcrRepository,
        awsServiceNames.awsEcsCluster,
        awsServiceNames.kubernetesNode,
        awsServiceNames.kubernetesPod,
    ],
    [awsServiceCategories.database]: [
        awsServiceNames.awsRdsCluster,
        awsServiceNames.awsElasticacheReplicationGroup,
        awsServiceNames.awsElasticacheCluster,
        awsServiceNames.awsDynamodbTable,
        awsServiceNames.awsDbInstance,
        awsServiceNames.awsRedshiftCluster,
    ],
    [awsServiceCategories.devops]: [
        awsServiceNames.awsCloud9EnvironmentEc2,
        awsServiceNames.awsCodeBuild,
        awsServiceNames.awsCloudformationStack,
    ],
    [awsServiceCategories.integration]: [
        awsServiceNames.awsSnsTopic,
        awsServiceNames.awsSqsQueue,
        awsServiceNames.awsSesEmailIdentity,
        awsServiceNames.awsMwaaEnvironment,
    ],
    [awsServiceCategories.iot]: [awsServiceNames.awsIotThing],
    [awsServiceCategories.management]: [awsServiceNames.awsCloudwatchMetricAlarm],
    [awsServiceCategories.networking]: [
        awsServiceNames.awsApiGatewayRestApi,
        awsServiceNames.awsLb,
        awsServiceNames.awsLbListener,
        awsServiceNames.awsNatGateway,
        awsServiceNames.awsNetworkAcl,
        awsServiceNames.awsRoute53Record,
        awsServiceNames.awsRouteTable,
        awsServiceNames.awsSubnet,
        awsServiceNames.awsInternetGateway,
        awsServiceNames.awsElb,
        awsServiceNames.awsApiGatewayStage,
        awsServiceNames.awsVpc,
        awsServiceNames.awsApiGatewayResource,
        awsServiceNames.awsRoute53Zone,
        awsServiceNames.awsCloudfrontDistribution,
        awsServiceNames.awsCustomerGateway,
        awsServiceNames.awsEip,
        awsServiceNames.awsNetworkInterface,
        awsServiceNames.awsEc2TransitGateway,
        awsServiceNames.awsEc2TransitGatewayVpcAttachment,
        awsServiceNames.awsVpnConnection,
        awsServiceNames.awsVpnGateway,
    ],
    [awsServiceCategories.security]: [
        awsServiceNames.awsKmsKey,
        awsServiceNames.awsCognitoUserPool,
        awsServiceNames.awsCognitoIdentityPool,
        awsServiceNames.awsSecretsManagerSecret,
        awsServiceNames.awsSecurityGroup,
        awsServiceNames.awsWafV2WebAcl,
    ],
    [awsServiceCategories.storage]: [
        awsServiceNames.awsEfsMountTarget,
        awsServiceNames.awsS3Bucket,
        awsServiceNames.awsEfsFileSystem,
    ],
};
export default hierarchy;
