export const colors = {
    black: "#000000",
    white: "#fafafc",
    offBlack: "#141316",
    darkGray: "#222225",
    midGray: "#36363d",
    borderGray: "#D9DCDF",
    disabledGray: "#606063",
    lightGray: "#6c6c77",
    lightGrayTransparent: "#6c6c774d",
    lighterGray: "#bdbdcc",
    lightBlueGray: "#9e9eaa",
    brandPurple: "#5d5adf",
    brandPurpleLight: "#888ffb",
    brandPurpleDark: "#3e47bf",
    darkerBrandPurple: "#312f7d",
    teal: "#48d2ca",
    midTeal: "#4ed8d3",
    darkTeal: "#268388",
    darkerTeal: "#262F33",
    brightTeal: "#71f3eb",
    brightGreen: "#82ffc6",
    darkGreen: "#70dca8",
    limeGreen: "#c3f895",
    lightLimeGreen: "#b8ffbd",
    blue: "#4179e4",
    red: "#f33f68",
    apricot: "#f1bb87",
    lightRed: "#ff5e83",
    salmon: "#ffb294",
    imageOverlayColor: "#7e7f9d69",
    textButtonHover: "#adb1ee3d",
    transparentBrand: "#666ee8b3",
    accentPurple: "#7f59f1",
    awsOrange: "#ffb400",
    azureGreen: "#44d8cf",
    gcpBlue: "#4181e4",
    yellowOrange: "#f7c58e",
    cornflowerBlue: "#666ee8",
    gradientStart: "#2c2c31",
    gradientEnd: "#202023",
    coolGray: "#868E93",
    costGray: "#DEE1E2",
    monochromeGray: "#4B4B58",
    transparent: "#ffffff00",
};

const palette = {
    mode: "dark",
    action: {
        selected: colors.salmon,
    },
    background: {
        default: colors.offBlack,
        gradientStart: colors.gradientStart,
        gradientEnd: colors.gradientEnd,
    },
    primary: {
        light: colors.brandPurpleLight,
        main: colors.brandPurple,
        dark: colors.brandPurpleDark,
        darker: colors.darkerBrandPurple,
    },
    secondary: {
        main: colors.teal,
        light: colors.brightGreen,
    },
    error: {
        main: colors.red,
        light: colors.lightRed,
    },
    success: {
        light: colors.brightGreen,
        main: colors.teal,
    },
    text: {
        primary: colors.white,
    },
    feedbackIcon: {
        background: colors.midTeal,
        backgroundHover: colors.brightGreen,
        fill: colors.offBlack,
    },
    common: {
        black: colors.black,
        gcpBlue: colors.gcpBlue,
        awsOrange: colors.awsOrange,
        azureGreen: colors.azureGreen,
        offBlack: colors.offBlack,
        white: colors.white,
        lightGray: colors.lightGray,
        lightGrayTransparent: colors.lightGrayTransparent,
        lighterGray: colors.lighterGray,
        lightBlueGray: colors.lightBlueGray,
        midGray: colors.midGray,
        darkGray: colors.darkGray,
        red: colors.red,
        brightTeal: colors.brightTeal,
        midTeal: colors.midTeal,
        apricot: colors.apricot,
        salmon: colors.salmon,
        accentPurple: colors.accentPurple,
        brightGreen: colors.brightGreen,
        limeGreen: colors.limeGreen,
        lightLimeGreen: colors.lightLimeGreen,
        textButtonHover: colors.textButtonHover,
        transparentBrand: colors.transparentBrand,
        imageOverlayColor: colors.imageOverlayColor,
        disabledGray: colors.disabledGray,
        darkTeal: colors.darkTeal,
        darkerTeal: colors.darkerTeal,
        blue: colors.blue,
        yellowOrange: colors.yellowOrange,
        cornflowerBlue: colors.cornflowerBlue,
        gradientStart: colors.gradientStart,
        gradientEnd: colors.gradientEnd,
        teal: colors.teal,
        coolGray: colors.coolGray,
        costGray: colors.costGray,
        lightRed: colors.lightRed,
        monochromeGray: colors.monochromeGray,
        darkerBrandPurple: colors.darkerBrandPurple,
        transparent: colors.transparent,
        brandPurpleLight: colors.brandPurpleLight,
    },
};

export default palette;
